### ISSUE TITLE
Integration with A/B Street as 'third zoom level'

### ISSUE THREAD

**Issue by mvl22** [cyipt/actdev#28]
An initial proposal is under consideration for whether ActDev could provide an integration with A/B Street, in order to provide a 'third zoom level' that would act as a visualisation of the network that results from the model, really bringing it to life.

In the initial prototype, the suggestion is that this would show the results arising from a manually-modified OSM network around a site in the pilot dataset. This rests on an assumption that such an ideal network could in future be automatically generated, not withstanding the natural role of intuition of a designer.

Note that this would essentially form a prototype demonstrating such integration, but it would need to be very clearly caveated to users that modification of the network within A/B Street would not result in changes to the uptake model, i.e. behaviour change. It could be very disconcerting for a practitioner to edit the network live in A/B Street but not find that behaviour change (levels of cycling) has resulted, contradicting what happens in the real world - this could send a very counter-productive message if not properly indicated. Future work would need to be done to reverse the order of processing.

Such integration needs to consider current limitations with regard to importing of cycle infrastructure that is separately tagged (which gives greater detail) and the routing model within it. Both are clearly important to the current project, even if they cannot be fully resolved within the timescale of the project.

**This ticket aims to scope out what integration work would be needed**, with a view for this proposal being taken forward. For instance, what file format would ActDev need to output, and what API provision does A/B street provide to consume this? What other issues would need to be resolved to make this work, at a technical level?

**Comment by Robinlovelace** [comment]
> what file format would ActDev need to output

CSV files representing OD movements, with mode shift scenarios for walking and cycling, like this: https://github.com/cyipt/actdev/blob/main/data-small/study_area_trumpington-test-od.csv



> and what API provision does A/B street provide to consume this

Good question, I imagine having some kind of schema/documentation on input data would be useful for the A/B Street project, and the question of how much processing is done in R vs Rust before the data is consumed (see a-b-street/abstreet#24 and discussion there for example) is still open. All doable though and in fact solvable in multiple ways in multiple languages. My question is which is likely to be the most efficient solution for this project and longer-term (raising the possibility of a codebase/package that outputs datasets representing scenarios of change to be consumed by A/B Street/SUMO/other but that's for another project).

> What other issues would need to be resolved to make this work, at a technical level?

Some of these are discussed in initial scoping document, I couldn't see any blockers in there and it seems we have a way to debug issues that do arise as illustrated in https://github.com/cyipt/actdev/issues/26#issuecomment-758723208 but I think this is a very good question in need of careful thought.

**Comment by mvl22** [comment]
> CSV files representing OD movements, with mode shift scenarios for walking and cycling, like this

Great; seeing that makes things much clearer in my head now. Presumably in our case there would be a lot more lines than this (as per our discussion to spread out locations), and of course the cryptically-named fields `geo_code1`, `geo_code2` would be replaced with lon/lat.

> schema/documentation on input data

Thanks; once we have that, I can give further thought as to how a UI might best handle the handoff between the two 'zoom levels'.

**Comment by dabreegster** [comment]
For context, https://docs.google.com/document/d/1xb5VW09DgFeNxyMCVYg_uo_torqCBqEE0Uxzl_11OtA/edit?usp=sharing is where these ideas were first discussed. This issue could consolidate specific work items, with the doc being the place to figure out what's in scope.

> manually-modified OSM network around a site in the pilot dataset. This rests on an assumption that such an ideal network could in future be automatically generated, not withstanding the natural role of intuition of a designer.

Could you clarify this part please -- are you referring to the "Model future buildings" section of the doc? I'm not proposing maintaining a fork of the OSM data with arbitrary local edits just for the integration. If there's not an appropriate schema to tag the possible new buildings, then any way of specifying them -- a .osmc we can merge in, a GeoJSON file, etc would all work.

>  Future work would need to be done to reverse the order of processing.

Agreed this needs to be communicated clearly. I can discuss with abst's UX designer. When somebody edits cycle infrastructure on the map, there are 3 time-frames that can be simulated -- the change happening immediately during a live simulation, the "next week" with people continuing to take the same trips with the same mode but possibly altering their route, and the long-term changes, with mode changes. https://github.com/dabreegster/abstreet/issues/448 tracks this last option, but I would like to decide whether starting it is in scope for this integration or not.

> Such integration needs to consider current limitations with regard to importing of cycle infrastructure that is separately tagged

https://github.com/dabreegster/abstreet/issues/449 and https://github.com/dabreegster/abstreet/issues/330 track this. Getting separate cycleways working in A/B Street is hard, but I propose for this integration, we enable configuration just for the study areas to opt into experimental support, and focus first on exactly the situations that happen in these areas.

> what file format would ActDev need to output

A/B Street can read a full synthetic population using this format:
https://dabreegster.github.io/abstreet/trafficsim/travel_demand.html#custom-import

It looks like you have [OD data](https://github.com/cyipt/actdev/blob/main/data-small/study_area_trumpington-test-od.csv) like this so far. From that and the geocode zones, I can disaggregate that to individual trips, making some simple guesses for distributing people to particular buildings and generating departure times.

So an initial summary of the particular tasks, with more details still in the doc:
- Import a map for each study area. Input needed is the polygon boundary as GeoJSON, osmosis polygon, etc
- Decide how to supply proposed buildings, either as .osmc, upstreaming a change in OSM, using GeoJSON, etc
- Decide how to supply a synthetic population (disaggregated) or OD data (aggregated), and fully disaggregate for A/B Street

I can add more tasks based on the UI, web deployment, and routing sections in the doc, once we decide exactly what we want here.

**Comment by dabreegster** [comment]
The JSON format for simulation input data has a well-typed schema specified [in Rust](https://github.com/dabreegster/abstreet/blob/master/sim/src/make/external.rs). I intend to use protocol buffers or something similar to declare a proper schema at some point, but I don't think it should block integration here -- especially if the input instead is the OD summaries.

**Comment by mvl22** [comment]
I see this refers to the API documentation:

https://dabreegster.github.io/abstreet/dev/api.html

**Comment by dabreegster** [comment]
To clarify, that's the API for controlling just the simulation without a UI -- likely not relevant here. For this integration, the main API is likely some new format for OD data, unless all the disaggregation happens in R and we just use https://dabreegster.github.io/abstreet/trafficsim/travel_demand.html#custom-import

**Comment by Robinlovelace** [comment]
Nice schema:

<details>

```
{
  "scenario_name": "monday",
  "people": [
    {
      "origin": {
        "Position": {
          "longitude": -122.303723,
          "latitude": 47.6372834
        }
      },
      "trips": [
        {
          "departure": 10800.0,
          "destination": {
            "Position": {
              "longitude": -122.3075948,
              "latitude": 47.6394773
        }
          },
          "mode": "Drive"
        }
      ]
    }
  ]
}
```

</details>

I would like to output data in that format, will make us think carefully about scenarios and encourage more detail which is a good thing, starting with a-b-street/abstreet#24. For the time being the suggestion to:

>  disaggregate that [OD data already provided so far] to individual trips, making some simple guesses for distributing people to particular buildings and generating departure times.

is a safe default.

**Comment by dabreegster** [comment]
Status update: Separate cyclepaths and pedestrian plazas (highway=pedestrian in OSM) are now imported for Cambridge, with some issues. Robin's OD data is imported as an abst scenario, with hardcoded uniform distribution of departure times in the morning and afternoon. The 0.2.27 release (at https://github.com/dabreegster/abstreet/releases soon) has all these changes, and so does http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev&cambridge/maps/trumpington.bin

My next steps:

- Improve the quality of the Cambridge import (https://github.com/dabreegster/abstreet/issues/449)
  - Sort out duplicate bike lanes (https://github.com/dabreegster/abstreet/issues/330#issuecomment-761604799)
  - Continue work on automatically finding and merging short roads, to improve rendering, avoid gridlock in the simulation, and make editing the intersections easier for the user
  - Deal with some buildings and parking lots that aren't imported (because they're not snapping to a road connection properly)
- Improve the OD -> scenario process
  - Currently around 100 cancelled trips in the baseline, because of routing / snapping to the wrong border intersection
- Draw new roads/buildings for the development sites
  - Since this won't be upstreamed in OSM until construction actually starts, try out the local workflow with ID and JOSM and identify any blockers.

As more study areas and OD data's generated, I can improve the automation for importing. I suspect it's too early to focus on the UI and web deployment tasks from the google doc.

Later goals still include improving A/B Street's routing (by changing the cost function, or possibly using a table of edge weights from CycleStreets) and having some kind of automatic mode choice change happen (https://github.com/dabreegster/abstreet/issues/448).

**Comment by mvl22** [comment]
> One thing missing from that schedule: adding a button to open A/B Street for one of the sites? I hope from your end, it shouldn't be hard -- when the view is near one of the study areas, enable a button on the right panel. Upon clicking, open a URL like `http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev&cambridge/maps/trumpinton.bin&cam=18/52.20565/0.13871` (in a new tab?). The 3 details we could hash out:
> 
> - The `cam` parameter is the zoom/center lat/center lon that OSM uses
> - The two map names right now are `cambridge/maps/trumpington` and `cheshire/maps/chapelford.bin`; maybe these can be inferred from existing study area names, or maybe we need to add a field, or maybe I need to rename things.
> - We need to set up a deployment procedure to copy over the static files for abst to your webserver. I can give you a simple shell script to produce these (that would be slow the first time on a particular machine, due to installing Rust and the initial compile), or cut a release whenever we need and send you the files by Dropbox or something else.
> 
> Let me know if I should start a separate issue for this, or we can repurpose a-b-street/abstreet#28.

Can the .bin file (NB typo "trumpinton") be added to the repo, in the same way that the data is?

It can be added to actdev-ui in a new folder - that repo is already auto-deploying regularly.

Or, if it can be loaded remotely via a URL, it can be added as a 'release' in the main repo, to avoid it inflating the .git/ repo size, as per these files:
https://github.com/cyipt/actdev/releases

**Comment by dabreegster** [comment]
> Can the .bin file (NB typo "trumpinton") be added to the repo, in the same way that the data is?

Sure. The binary map files are about 50MB for Chapelford and 30MB for Great Kneighton. There's also an `index.html`, 13MB `.wasm`, and a few small auto-generated `.js` files to deploy.

So the process would be for me to upload the abst files needed to the actdev release, and those get automatically deployed when the release assets change?

**Comment by dabreegster** [comment]
> So the process would be for me to upload the abst files needed to the actdev release, and those get automatically deployed when the release assets change?

After looking at how actdev-ui works and the cronjob there, I think I can answer my own question: no. We'd just put the .wasm, .bin, .js, .html, etc files in the actdev release assets, and directly link to them. We're just using github as a fileserver.

In the event that doesn't work for the smaller files (.html, .wasm), because github might not send the correct content-type headers, we could add those to the actdev-ui repo directly. They wouldn't change often (I'd batch some changes to abst as a "release") and the size would be around 13MB, dominated by the .wasm. The larger .bin map/scenario files can be hosted by github, because there's no content-type or other headers needed.

**Comment by mvl22** [comment]
> We'd just put the .wasm, .bin, .js, .html, etc files in the actdev release assets, and directly link to them. We're just using github as a fileserver.

I suggest if you create a new directory, e.g. abstreet/ at top-level there, and add any assets that are required (sorry, I'm still not clear yet how exactly A/B Street runs in filesystem terms), that should come through to the site, and presumably be minimally working from that directory. We can then see how to launch it from other places within the UI (i.e. other launching points of the directory structure).

**Comment by Robinlovelace** [comment]
Can we put them as releases to avoid adding more binary files to to the git history?

**Comment by mvl22** [comment]
That was my suggestion:

> Or, if it can be loaded remotely via a URL, it can be added as a 'release' in the main repo, to avoid it inflating the .git/ repo size, as per these files

but as Dustin says:

> github might not send the correct content-type headers, we could add those to the actdev-ui repo directly

Let's see what happens when Dustin tries - what he suggested above (the "After looking at" posting) is a sensible two-step trial.

**Comment by dabreegster** [comment]
I just tried creating a new release and adding the ~100MB of abst assets. The problem with github's release assets is that the file list is flat; the web UI doesn't seem to let me preserve directory structure. That's an issue, because ultimately the filesystem needs to look something like this:
![Screenshot from 2021-02-08 11-50-28](https://user-images.githubusercontent.com/1664407/107273393-da02e100-6a03-11eb-9e3e-386fb036b243.png)

Option 1: I can create a new repo, `cyipt/actdev-abstreet`, and commit the ~100MB there. We can modify https://github.com/cyipt/actdev-ui/blob/master/.cron.template to also pull down this repo, using the server to host, not github.

Option 2: I can upload that bundle to this repo's release assets as a .zip. We can make https://github.com/cyipt/actdev-ui/blob/master/.cron.template `wget` and `unzip` that file. Still winds up using the server to host, not github.

I'd lean towards the second option. @mvl22, thoughts?

Also I need to make another tweak to the abst code to change the base URL where it looks for files to wherever things wind up being hosted. I might be able to make this use relative paths; I'll try that out, to simplify things on my end.

**Comment by mvl22** [comment]
Yes, I suggest just zip it and I’ll add the unzipping to the auto-deploy.

**Comment by dabreegster** [comment]
Thanks! https://github.com/cyipt/actdev/releases/download/0.1.3/abst_actdev.zip

**Comment by mvl22** [comment]
That zip is now downloaded to /abstreet/ on the site (renamed from abst_actdev/ -> abstreet/ ).

However, I can't seem to work out what the full URL would be - presumably something like:

https://actdev.cyipt.bike/abstreet/?--dev&cambridge/maps/great_kneighton.bin.gz

**Comment by mvl22** [comment]
Just a quick note to flag up the need to ensure you use the same site name as those in this file for the data filenames, for consistency:
https://github.com/cyipt/actdev/blob/main/data-small/all-sites.geojson

We'll then be able to pick up the right one in the UI automatically.

**Comment by dabreegster** [comment]
> However, I can't seem to work out what the full URL would be

No `.gz`, but otherwise right. To add emphasis on the study area, `&study_area=great_kneighton`. The version uploaded yesterday on github releases still tries to read data from S3, so it doesn't work yet. I fixed this yesterday, and just updated the .zip asset. What's the update frequency set to, for my own knowledge?

>  use the same site name as those in this file for the data filenames

I'm still not sure how to handle this. A/B Street is divided up into individual maps, using the study area as the boundary. Each map is currently named by a city and district, allowing Leeds to be broken up into pieces, for example. I spot tresham and priors-hall as two sites both on the outskirts of Corby. Maybe the study areas mostly overlap here, and a single map handles them, or maybe not. Those cases could be expressed as "corby/maps/tresham" and "corby/maps/priors-hall" if not. But picking the nearest city is also a bit brittle for some of these suburbs; maybe the region name used by Geofabrik, which is northamptonshire in this case, is a better pick.

Additionally, I'm about at the point of introducing a third level of hierarchy in the city/district scheme, likely country.

I think I'll insulate actdev from all of this, and just parameterize on the site name from `all-sites.geojson`, and internally map that to the ever-evolving city/map scheme. Will look into this, along with importing all of the new study areas, later today.

**Comment by mvl22** [comment]
> No .gz, but otherwise right.

I had tried that, but it still doesn't work:

https://actdev.cyipt.bike/abstreet/?--dev&cambridge/maps/great_kneighton.bin

**Comment by Robinlovelace** [comment]
Works for me: 

![image](https://user-images.githubusercontent.com/1825120/107397425-8b823f00-6af6-11eb-86da-06c6c94d760d.png)


Oh, no it doesn't!

**Comment by mvl22** [comment]
> What's the update frequency set to, for my own knowledge?

None yet; it's currently just a downloaded copy of the release, until we know whether release numbers are going to change (can't auto-deploy if the URL changes).

**Comment by mvl22** [comment]
> I'm still not sure how to handle this. A/B Street is divided up into individual maps, using the study area as the boundary.

One-to-one is presumably fine at the moment? I.e. separate for trumpington and great-knighton, as although they are close, they presumably have different modelling anyway.

**Comment by mvl22** [comment]
> just updated the .zip asset

Thanks; now redownloaded, and that is coming through fine now:

https://actdev.cyipt.bike/abstreet/?--dev&cambridge/maps/great_kneighton.bin

Assuming we have a one-to-one mapping, can we get rid of the cambridge/maps/ bit of this URL? Then I can predictably link into the site moniker (e.g. great_knighton) and then clean up the public URL with a RewriteRule.

**Comment by dabreegster** [comment]
> until we know whether release numbers are going to change 

Ah, fair. How do you want to coordinate releases then? I just edited the 0.1.3 release, deleted the old .zip, and uploaded a replacement with yesterday's fixes. Should the process during the next ~month of heavy development be to create a new github release in the 0.1.x space?

> One-to-one is presumably fine at the moment

Yes, this probably makes the most sense. abst breaking up cities into districts is for a different use case than actdev; here we don't really care that two sites happen to be close. I'll think about the namespacing that'll make sense.

> can we get rid of the cambridge/maps/ bit of this URL

Yes, let's say just the site name is the main input, and `&cam=Z/X/Y` is one of the main query params. Maybe `actdev.cyipt.bike/abstreet/great_kneighton?cam=Z/X/Y` is what the user sees, and this gets rewritten to `actdev.cyipt.bike/abstreet/index.html?site=great_kneighton&cam=Z/X/Y` or something?

**Comment by mvl22** [comment]
> Ah, fair. How do you want to coordinate releases then?

I suggest Robin decides this. Personally I'd prefer that we just keep a single release so that we have a URL that doesn't change. But I think Robin seems keen on versioning every change and keeping the binaries for each just in case we want to go back.

> &cam=Z/X/Y

Out of interest, does whatever framework you use enable a hash to be read, i.e. exactly matching the JS approach of Leaflet etc?

**Comment by Robinlovelace** [comment]
> Ah, fair. How do you want to coordinate releases then?

We discussed this just now and I think auto-detecting the latest release and going with that is the way forward.

If for the next release you can put all the sites up (massively over-delivering on the MVP of 2 sites we agreed : ) and @mvl22 implements something like the code below it should update - or we could just hardcode it and communicate before the next release. My vote is the automated solution if not too much hassle on the deploy side:

```bash
get_latest_release() {
  curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
    grep '"tag_name":' |                                            # Get tag line
    sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
}


get_latest_release cyipt/actdev
# 0.1.3
```

Source: https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c

**Comment by Robinlovelace** [comment]
> I suggest Robin decides this.

Hopefully that was a decision but I'm not 100% sure I answered the question so let me know if there are other options to decide between here.

**Comment by mvl22** [comment]
> implements something like the code below

Yes, assume I'll do that then.

It occurs to me of course that we can always delete old versions to avoid accruing masses of huge 20MB files that we no longer need.

**Comment by dabreegster** [comment]
New releases with automated deployment SGTM.

>  But I think Robin seems keen on versioning every change and keeping the binaries for each just in case we want to go back.

From the abst perspective, this is always possible with moderate hassle. Checking out an older git commit is easy; the only extra step is to rebuild all of the maps using that commit as well. Not hard, but I wouldn't want to do it regularly.

> Out of interest, does whatever framework you use enable a hash to be read, i.e. exactly matching the JS approach of Leaflet etc?

I could make this work, but if it's not tough to use query parameters from your side, I'd prefer to keep doing that. I'm transforming the URL query parameters into command-line flags internally (so actually, it'd be `--cam=z/x/y`, whoops) to keep things working the same on native and web. I'd prefer not to special case URL fragments, but I can if needed.

**Comment by mvl22** [comment]
No, don't spend time on the map hash stuff.

Let me know when the simplified version without the cityname/maps/ hierarchy is there.

**Comment by dabreegster** [comment]
Here we go: https://github.com/cyipt/actdev/releases/download/0.1.4/abst_actdev.zip
Up to 150MB compressed with all the new maps.

The URLs should look like this: `actdev.cyipt.bike/abstreet/?--dev&--actdev=ebbsfleet&cam=14/53.3637/-2.1772`
`--dev` skips the title screen. `--actdev` takes the site name, corresponding to dir names in `data-small`. And `--cam` is still partly broken, but will eventually set the camera view.

As we figure out what pieces of A/B Street should get disabled (like its title screen), I'll likely make `--actdev` imply `--dev` and some other things internally.

**Comment by mvl22** [comment]
Thanks; that's there now, but fyi I'm getting a WASP RuntimeError.

**Comment by dabreegster** [comment]
Argh, it's because I can't remember my own URL->CLI madness. `--cam`

https://actdev.cyipt.bike/abstreet/?--dev&--actdev=ebbsfleet&--cam=14/53.3637/-2.1772

But the camera setting seems to not be working, even though it was (by CLI) yesterday. I'll have that fixed by tomorrow; right now, looks like the param just gets ignored.

**Comment by mvl22** [comment]
Basic integration now in place as per screenshot below :)

NB: I know the addition of popups to the main (large) Study area lozenge will mean that the whole area ends up potentially catching a second popup. This is a known issue which needs to be resolved by (a) disabling click-through propagation, and (b) adding explicit layer ordering support (which manifests itself as a problem in other odd ways). I will fix these but it may be a day or two as these are a bit complex.

![Screenshot 2021-02-10 at 00 58 56](https://user-images.githubusercontent.com/361423/107449275-2f8dd980-6b3b-11eb-985e-98f354f8ad3d.png)

**Comment by mvl22** [comment]
I've tried to simplify the URL but this isn't working:

https://actdev.cyipt.bike/abstreet/great-knighton

... because of course the Javascript (unlike a server-side script) now can't see the query string, which has been written away. Oh well.

**Comment by dabreegster** [comment]
> Basic integration now in place as per screenshot below

Woohoo, this is awesome!

> the Javascript (unlike a server-side script) now can't see the query string

I could parse this type of URL instead if needed. One thing I'm planning to add soon is updating the URL when the player moves the camera or changes maps. Likely I'd implement that by just transforming the current URL, so any rewriting rules would still work.

**Comment by dabreegster** [comment]
https://github.com/cyipt/actdev/releases/tag/0.1.5 made a small fixed with `--cam` to support fractional zoom. I tried a few examples around Allerton Bywater on my end, and it seems to match up. If possible, pass `--cam=...` and copy from the slippy map's current state.

**Comment by Robinlovelace** [comment]
Amazing work on the JS side and A/B Street side. Look forward to giving it a spin!

**Comment by Robinlovelace** [comment]
Closing as essentially done.
